%tokens ;
%goal source ;

alpha math colon --> alpha math ;
alpha math omega --> clause ;
alpha omega --> clause ;
alpha simp --> alpha math ;
beginning close ( terminator | stmt ) --> stmt ;
beginning stmt --> beginning ;
case_head casey clause --> case_head ;
case_head close terminator --> stmt ;
case_head stmt --> case_head ;
casey clause --> case_head ;
clause stmt --> stmt ;
cond clause stmt elsie --> clause ;
cond clause stmt --> stmt ;
elsie --> intro ;
exp math simp !simp --> math 4 ;
exp simp !simp --> math 3 ;
intro stmt --> stmt ;
math close --> stmt close ;
math colon --> intro ;
math math --> math ;
math simp --> math ;
math stmt --> stmt ;
math terminator --> stmt ;
mod_scrap ( terminator | semi ) --> stmt ;
mod_scrap --> simp ;
open case_head close --> math ;
open close --> math ;
open math case_head close --> math ;
open math close --> math ;
open math colon --> open math ;
open math proc intro --> open math ;
open math semi --> open math ;
open math var_head intro --> open math;
open proc intro --> open math ;
open simp --> open math ;
open stmt close --> math ;
open var_head intro --> open math ;
proc beginning close terminator --> stmt ;
proc stmt --> proc ;
record_head intro casey --> casey ;
record_head --> case_head ;
semi --> terminator ;
simp close --> stmt close ;
simp colon --> intro ;
simp math --> math ;
simp mod_scrap --> mod_scrap ;
simp simp --> simp ;
simp terminator --> stmt ;
stmt stmt --> stmt ;
terminator --> stmt ;
var_head beginning --> stmt beginning ;
var_head math colon --> var_head intro ;
var_head simp colon --> var_head intro ;
var_head stmt --> var_head ;
# [ !source ] --> [ source ] ;
